version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: newschatbot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - newschatbot_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: newschatbot_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    environment:
      - QDRANT_ALLOW_ANONYMOUS_WRITES=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - newschatbot_network

networks:
  newschatbot_network:
    driver: bridge

volumes:
  redis_data:
  qdrant_data: 